imports:
    - { resource: '/home/allflame/src/php/phalcon-sandbox/vendor/vain/config/config/di.yml' }
    - { resource: '/home/allflame/src/php/phalcon-sandbox/vendor/vain/http/config/di.yml' }
    - { resource: '/home/allflame/src/php/phalcon-sandbox/vendor/vain/phalcon/config/di.yml' }

services:
    app.controller.indexController:
        class: App\Controller\IndexController
